baseURL = "http://walkurehhh.github.io"
languageCode = "zh-Hans"
enableRobotsTXT = true
title = "LYH's Blog"
theme = "dream"
hasCJKLanguage = true
publishdir = "../publish"

#LavenderBlush
[params]
  background = "#f2cac9"
  backgroundImage = "/img/1.jpg"
  linkColor = "seagreen"

  # dark mode c48fa4
  defaultDark = true
  backgroundDark = "#b36d61"
  backgroundImageDark = "/img/1.jpg"
  darkLinkColor = "darkseagreen"
  # darkNav = true
  # dark404 = true

  images = [""]

  author = "Erwin"
  description = "Li Yuanhao's Blog"
  avatar = "/img/ichigo_square.jpg"
  headerTitle = "Li Yuanhao's Blog"
  motto = "python yyds"
  # maxTags = 5
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  #rss = true

  utterancesRepo = "walkureHHH/utterances_repo"

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""
  # VALINE_LANGUAGE = ""

  email = "erwinli@qq.com"
  #twitter = ""
  #facebook = ""
  #instagram = ""
  # mastodon = ""
  #linkedin = ""
  github = "walkureHHH"
  #stackoverflow = ""
  #codepen = ""

  siteStartYear = 2020

  favicon = "/favicon.ico"

  highlightjs = true
  #highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsCDN = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  highlightjsTheme = "github"
  #highlightjsThemeDark = "gruvbox-dark"
  highlightjsThemeDark = "dracula"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  # reversePostAndAside = true
  # shareInAside = true
  fixedNav = true
  # collapsibleTags = true
  # collapseBySummary = true

  [params.advanced]
    customCSS = ["css/background.css"]
    # customJSBefore = []
    # customJS = []

  [params.experimental]
    jsDate = true
    jsDateFormat = "yyyy-MM-dd"